// "use client";
// import type { Metadata } from "next";
// import { usePathname, useRouter } from "next/navigation";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   const pathname = usePathname(); // to check current route
//   const hideHeaderFooter = ["/login", "/signup"].includes(pathname);

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//          {!hideHeaderFooter && <header />}
//         <main>{children}</main>
//         {!hideHeaderFooter && <footer />}
//       </body>
//     </html>
//   );
// }


// src/app/layout.tsx  (Server component)
import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // relative to app/
import { CartProvider } from "./context/CartContext";

export const metadata: Metadata = {
  title: "My Restaurant",
  description: "Ordering made simple",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* ClientLayout will show Header/Footer except on auth pages */}
        <CartProvider>
          <ClientLayout>{children}</ClientLayout>
        </CartProvider>

      </body>
    </html>
  );
}
